// components/data/projects.js
const projects = [
  {
    id: 24,
    title: "AI ADMINISTRATIVE ASSISTANT",
    description: "AI-powered assistant designed to streamline administrative workflows, automate repetitive tasks, and enhance productivity. The interface organises the day around a single workspace: chat, captured ideas, tasks, calendar and saved items in one rail, with work grouped into projects so context is never lost between them.",
    tags: ["UX/UI"],
    role: "Product Designer",
    industry: "Productivity & AI",
    toolkit: "Figma",
    color: "#2F6BFF",
    cover: "/eli.png",
    link: null
  },
  {
    id: 1,
    title: "DESIGN A FOOD DELIVERY APP FOR A CAFE",
    description: "UX case study focused on accessibility. This app is designed for a local café, allowing customers to browse drinks and pastry options, customize their coffee orders, and choose between in-store pickup or home delivery. The design prioritizes clarity, ease of use, and inclusivity for all users.",
    tags: ["UX/UI"],
    role: "UX Research, Usability Testing, UI Design, Prototyping",
    industry: "Food & Beverage",
    toolkit: "Figma, Google Sheets",
    color: "#708AFB",
    cover: "/cafeapp.webp",
    link: "/cases/blue"
  },
  {
    id: 2,
    title: "DESIGN A RESPONSIVE WEBSITE FOR A CAFE",
    description: "Designed a responsive website for a local café to enhance user experience and increase online orders. Targeted young professionals and loyal customers looking for a fast, intuitive way to order or make reservations.",
    tags: ["UX/UI"],
    role: "UX Research, Usability Testing, UI Design, Prototyping",
    industry: "Food & Beverage",
    toolkit: "Figma, Google Sheets",
    color: "#6783c0",
    cover: "/cafeweb.webp",
    link: "/cases/blueweb"
  },
  {
    id: 3,
    title: "DR. KARLA PÉREZ – DENTAL CLINIC WEBSITE",
    description: "Designed and developed a comprehensive web presence for Dr. Karla Pérez’s dental clinic. The project focused on a 'Patient-First' UX approach, simplifying the appointment booking process and presenting medical services through a clean, trustworthy interface. Built with a responsive frontend to ensure seamless access across all devices.",
    tags: ["UX/UI", "Frontend"],
    role: "UX/UI Designer & Frontend Developer",
    industry: "Healthcare & Dental Services",
    toolkit: "React, Tailwind CSS, Figma, Framer Motion",
    color: "#84a0c5",
    cover: "/drakarla.png",
    link: "https://drakarlaperez.com"
  },
  {
    id: 4,
    title: "POS SYSTEM (NDA REDACTED)",
    description: "Designed a comprehensive Point of Sale (POS) system from the ground up, focusing on scalability for retail and apparel industries. The project involved creating a complex architecture for inventory management with multi-variant support (SKU, stock, and dynamic pricing). Due to privacy and NDA constraints, the presentation focuses on the modular Design System and user flows developed to optimize checkout speed and administrative control.",
    tags: ["UX/UI", "Product Design"],
    // Manda en el destacado de su categoría. Sin esta marca, el showcase
    // simplemente coge el primero de la lista.
    featured: true,
    role: "Lead Product Designer",
    industry: "Retail & FinTech",
    toolkit: "Figma, Design Systems, User Flows",
    color: "#00D1FF",
    cover: "/POS.png",
    link: "/"
  },
  {
    id: 23,
    title: "DOMINÓ – ONLINE MULTIPLAYER GAME",
    description: "Design and development of an online dominoes game for playing with friends straight from the browser. Covers the whole flow: creating a room with a shareable code and invite link, setting the number of players and the target score, a lobby that fills up as people join, an illustrated how-to-play section, and the match board itself. Currently in development.",
    tags: ["UX/UI", "Frontend"],
    role: "Product Designer & Frontend Developer",
    industry: "Games & Entertainment",
    toolkit: "Figma, React, Tailwind CSS",
    color: "#1F6B3A",
    cover: "/domino.png",
    // En desarrollo: todavía no hay nada a lo que enlazar.
    link: null
  },
  {
    id: 5,
    title: "TRIPFLOW TRAVEL BUDGET APP (UX CHALLENGE)",
    description: "Designed and prototyped a financial control app for travelers as part of a technical challenge. Starting from a blank canvas, I developed the visual identity and core features: an expense dashboard with real-time budget alerts, trip creation with spending limits, and an optimized quick-entry system for transactions. The project highlights my ability to translate complex user needs into high-fidelity functional prototypes.",
    tags: ["UX/UI"],
    role: "Product Designer (Solo)",
    industry: "Fintech & Travel",
    toolkit: "Figma, Prototyping, UX Research",
    color: "#385BF0",
    cover: "/tripflow.png",
    link: "/"
  },
  {
    id: 6,
    title: "COLOREANDO SUEÑOS – LANDING PAGE DESIGN",
    description: "Designed and developed a vibrant, welcoming landing page for a preschool and early stimulation center. The project focused on building trust with parents through an intuitive UI, warm color theory, and clear communication of educational programs. The interface was optimized for lead generation, featuring a simplified enrollment inquiry system and a fully responsive layout for mobile-first users.",
    tags: ["UX/UI"],
    role: "UX/UI Designer & Frontend Developer",
    industry: "Education & Childcare",
    toolkit: "React, Tailwind CSS, Figma, Canva",
    color: "#FFB000",
    cover: "/coloreando.png",
    link: "/"
  },
  {
    id: 7,
    title: "ECOLOGICAL PEST CONTROL WEBSITE",
    description: "Designed a high-conversion landing page for an ecological pest control company. The project focused on balancing industrial professionalism with environmental responsibility. I implemented a strategic information architecture that highlights key performance indicators (+200 protected homes) and a seamless appointment booking system. The UI prioritizes trust through clean layouts, service-specific iconography, and a mobile-optimized 'Quick Contact' flow.",
    tags: ["UX/UI"],
    role: "UX/UI Designer & Frontend Developer",
    industry: "Industrial & Domestic Services",
    toolkit: "React, Tailwind CSS, Figma, Lucide Icons",
    color: "#617e39",
    cover: "/fumigar.png",
    link: "/"
  },
  {
    id: 8,
    title: "ARCODE DOMINICANA WEBSITE DEVELOPMENT",
    description: "Led the visual identity design and frontend development for Arcode Dominicana. I translated complex UI prototypes into a high-performance functional website, ensuring a seamless user experience. The project focused on clean architecture, responsive design, and a modern aesthetic to position the brand effectively in the digital market.",
    tags: ["UX/UI", "Frontend"],
    role: "Design Lead & Frontend Developer",
    industry: "Software & Tech Services",
    toolkit: "React, JavaScript, Figma, Tailwind CSS",
    color: "#4459E1",
    cover: "/arcodedominicana.png",
    link: "https://arcodedominicana.com"
  },
  {
    id: 9,
    title: "BEN BARBER SUPPLY BRANDING & HOME PAGE DESIGN",
    description: "Developed the complete branding for Ben Barber Supply, including the logo and homepage design, based on the client's requirements. The project aimed to establish a strong visual identity and an intuitive user experience. The logo was crafted to reflect the brand’s personality, while the homepage was designed to highlight key products, improve usability, and increase customer engagement.",
    tags: ["UX/UI"],
    role: "UX Research, UI Design",
    industry: "Grooming & Retail",
    toolkit: "Figma, Canva",
    color: "#e08f63",
    cover: "/benbarber.webp",
    link: "/cases/ben"
  },
  {
    id: 10,
    title: "GL SILA WEBSITE DEVELOPMENT",
    description: "Led the UX design and fully developed both the frontend and a basic backend for GL SILA’s first official website. The project involved building a responsive and user-friendly interface to showcase the company’s services and products as an exporter and distributor of avocados and exotic fruits in the Dominican Republic. I worked from scratch using React and designed all the visual components with Canva, ensuring a cohesive and modern brand presence online.",
    tags: ["UX/UI", "Frontend", "Backend"],
    role: "UX Research, UI Design, Frontend Developer, Backend Developer",
    industry: "Export & Distribution",
    toolkit: "React, VS Code, Canva",
    color: "#048d8e",
    cover: "/glsila.webp",
    link: "https://glsila.com"
  },
  {
    id: 11,
    title: "BILLER ONE – ACADEMIC POS SYSTEM",
    description: "Developed as a core university project, Biller One is a modern POS system focused on the integration between responsive frontends and external APIs. I led the frontend development using React and Vite, implementing modern architectural patterns to ensure scalable state management and efficient transaction processing. This project served as a deep dive into building production-ready interfaces for complex service-oriented operations.",
    tags: ["Frontend", "Academic Project"],
    role: "Front-end Developer",
    industry: "Retail & FinTech",
    toolkit: "React, Vite, V0, Tailwind CSS",
    color: "#00F59B",
    cover: "/Billerone.jpg",
    link: "https://github.com/Coralinesp/BillerOne"
  },
  {
    id: 12,
    title: "TROPICAL WEATHER – ACADEMIC API PROJECT",
    description: "Developed as a technical university project, this weather application focuses on real-time data fetching and dynamic UI state management. I designed a high-contrast dark theme using a blue and purple palette to enhance visual comfort while delivering accurate meteorological data for the Dominican Republic. The project demonstrates proficiency in handling asynchronous API calls and translating JSON responses into a modern, user-friendly interface.",
    tags: ["Frontend", "Academic Project"],
    role: "Frontend Developer & Designer",
    industry: "Weather & Utility",
    toolkit: "React, OpenWeather API, Tailwind CSS, V0",
    color: "#A020F0",
    cover: "/weather.jpg",
    link: "https://github.com/Coralinesp/tropicalweather"
  },
  {
    id: 13,
    title: "WALLETMATE – ACADEMIC FINANCE PROJECT",
    description: "Developed as a technical university project, WalletMate is a personal finance tracker that emphasizes efficient data management and clean UI architecture. I implemented dynamic filtering systems to analyze financial health in real-time, focusing on the logic of categorizing transactions and handling complex user inputs. This project demonstrates my ability to build data-driven tools with a focus on both frontend performance and intuitive UX.",
    tags: ["Frontend", "Academic Project"],
    role: "Frontend Developer & Designer",
    industry: "Education / Fintech",
    toolkit: "React, Tailwind CSS, V0, Lucide Icons",
    color: "#C0FF00",
    cover: "/walletmate.jpg",
    link: "https://github.com/Coralinesp/WalletMate"
  },
  {
    id: 14,
    title: "HAMMER 3D MODELING PROJECT",
    description: "Developed a detailed 3D hammer model as part of a Blender course at ITLA. The project involved the full 3D pipeline, including sculpting high-resolution details, retopologizing for optimal topology, texturing for realism, and creating a final presentation scene. This hands-on experience allowed me to strengthen my understanding of digital sculpting, low-poly optimization, and material application in Blender.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art & Game Assets",
    toolkit: "Blender",
    color: "#cc9a98",
    cover: "/hammer.webp",
    link: "https://drive.google.com/file/d/1Tgslw2M-ySkghK3WHkibSiPqc1M0C2kG/view?usp=sharing"
  },
  {
    id: 15,
    title: "DENTAL CLINIC VFX – KARLA PÉREZ",
    description: "Created a visual effects composition for Karla Pérez's dental clinic using Blender and FSpy. The project involved camera matching with FSpy to accurately align 3D elements with a real-world photograph of the clinic. I integrated 3D graphics into the environment to simulate architectural signage and digital enhancements.",
    tags: ["3D Design"],
    role: "3D Artist, VFX Designer",
    industry: "Digital Art",
    toolkit: "Blender, fSpy",
    color: "#84a0c5",
    cover: "/karlavfx.webp",
    link: "https://drive.google.com/file/d/1UGj_MBcvadHDemX7z7GMUEgvdTQhUJ2u/view?usp=sharing"
  },
  {
    id: 16,
    title: "3D MOCKUPS FOR WEBSITE PRESENTATION",
    description: "Created a series of realistic 3D mockups using Blender to showcase website designs in visually compelling scenes. The models included devices such as laptops, phones, and tablets, allowing for dynamic and professional presentation of UI/UX projects. This project helped improve my skills in lighting, material setup, and product-style rendering.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art & Mockups",
    toolkit: "Blender",
    color: "#e08f63",
    cover: "/mockup.webp",
    link: "https://drive.google.com/file/d/1avFBVYMh8VcYXagGhdKGi_XDm_4TGMK_/view?usp=sharing"
  },
  {
    id: 17,
    title: "KODA CHARACTER DESIGN",
    description: "Designed and developed 'Koda,' a unique 3D character, from initial 2D concepts in Adobe Illustrator to detailed 3D modeling and texturing in Blender. This project showcased my skills in character creation and bringing artistic visions to life through a combined 2D and 3D pipeline.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art",
    toolkit: "Blender, Adobe Illustrator",
    color: "#8492cb",
    cover: "/koda.webp",
    link: "https://drive.google.com/file/d/1jjPTjqx87RuUpZ8cC7IgCgNOVHorcymC/view?usp=sharing"
  },
  {
    id: 18,
    title: "CHRISTMAS 3D SHORT FILM",
    description: "Collaborated on the creation of a heartwarming 3D animated short film for Christmas using Blender. My contributions included 3D modeling of environments, as well as texturing and lighting to establish the festive atmosphere. This project honed my skills in collaborative animation production and bringing a narrative to life through 3D art.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art",
    toolkit: "Blender",
    color: "#617e39",
    cover: "/christmas.webp",
    link: "https://drive.google.com/file/d/1xm3lYzFvYah4aNuMzHgtOLcSL3o1ETYQ/view?usp=sharing"
  },
  {
    id: 19,
    title: "PICANTE FM RADIO BOOTH 3D REDESIGN",
    description: "Undertook a comprehensive 3D redesign of the interior of the 'Picante FM' radio booth using Blender. This project involved 3D modeling of furniture, equipment, and architectural elements, along with detailed texturing and lighting to create a modern, functional broadcast environment.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art & Interior Design",
    toolkit: "Blender",
    color: "#d73d0e",
    cover: "/picante.webp",
    link: "https://drive.google.com/file/d/1M_NciEQ0WC5jJ6mFPD6UpOuSyLm_RLLd/view?usp=sharing"
  },
  {
    id: 20,
    title: "ROSE WALLPAPER",
    description: "Created a stylized 3D rose wallpaper using Blender, focusing on artistic composition and realism. The process included sculpting organic shapes, shading with custom materials, lighting the scene for a soft aesthetic, and rendering a high-resolution image suitable for backgrounds.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art",
    toolkit: "Blender",
    color: "#9d8eca",
    cover: "/wallpaper.webp",
    link: "https://drive.google.com/file/d/1ZTOV1gP_nhJjHjlvjHGRaG7Kzmf9il4w/view?usp=sharing"
  },
  {
    id: 21,
    title: "BMO 3D",
    description: "Modeled BMO, the beloved character from Adventure Time, as part of a personal 3D project using Blender. The process included creating clean hard-surface topology, applying stylized materials, and setting up a simple scene to showcase the character's playful design.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art",
    toolkit: "Blender",
    color: "#ccee04",
    cover: "/bmo.webp",
    link: "https://drive.google.com/file/d/1avv0Aq7TIpyuRXrruOKXIgaDtqAO31Ya/view?usp=sharing"
  },
  {
    id: 22,
    title: "3D CAMERA SONY",
    description: "Designed and modeled a realistic Sony camera in Blender as part of a personal 3D study focused on hard-surface modeling. This exercise helped me improve my precision modeling skills and gain a deeper understanding of product visualization in 3D.",
    tags: ["3D Design"],
    role: "3D Artist",
    industry: "Digital Art",
    toolkit: "Blender",
    color: "#7e90d0",
    cover: "/camera.webp",
    link: "https://drive.google.com/file/d/1CJuqkWu1-394dcmQvBrVpD6MQprdkU_3/view?usp=sharing"
  },
];

export default projects;